"""Add category_id and difficulty_id to question

Revision ID: 5143e38545da
Revises: 
Create Date: 2025-03-14 13:18:58.963618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5143e38545da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('difficulty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'difficulty', ['difficulty_id'], ['id'])
    op.create_foreign_key(None, 'question', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'difficulty_id')
    op.drop_column('question', 'category_id')
    # ### end Alembic commands ###
